issue: 1426871 Enable service status for non root
Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>

diff --git a/contrib/scripts/vma.init.in b/contrib/scripts/vma.init.in
--- a/contrib/scripts/vma.init.in
+++ b/contrib/scripts/vma.init.in
@@ -115,28 +115,35 @@ function do_restart()
     do_start
 }
 
-if ! check_permission; then
-    echo "root permission is required"
-    exit 1
-fi
+
+function do_check()
+{
+    if ! check_permission; then
+        echo "root permission is required"
+        exit 1
+    fi
+}
 
 case "$1" in
     start)
+        do_check
         do_start
-	    ;;
+        ;;
     stop)
-	    do_stop
-	    ;;
+        do_check
+        do_stop
+        ;;
     status)
         do_status
-	    ;;
+        ;;
     restart | force-reload)
-	    do_restart
-	    ;;
+        do_check
+        do_restart
+        ;;
     *)
-	    echo $"Usage: $0 {start|stop|status|restart|force-reload}"
-	    RETVAL=1
-	    ;;
+    echo $"Usage: $0 {start|stop|status|restart|force-reload}"
+    RETVAL=1
+    ;;
 esac
 
 exit $RETVAL
